//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.QuiAbl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings_AppConst : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_AppConst defaultInstance = ((Settings_AppConst)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_AppConst())));
        
        public static Settings_AppConst Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuiAblDb")]
        public string ProjectFile_DefaultExtension {
            get {
                return ((string)(this["ProjectFile_DefaultExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quittungsdatenbank (*.QuiAblDb)|*.QuiAblDb|QuiAbl (*.xml)|*.xml|Alle Dateien (*.*" +
            ")|*.*")]
        public string ProjectFile_FilterList {
            get {
                return ((string)(this["ProjectFile_FilterList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ProjectFile_FilterIndex {
            get {
                return ((int)(this["ProjectFile_FilterIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1;2;3;4;5")]
        public string ProjectFile_VersionCompatibleNative {
            get {
                return ((string)(this["ProjectFile_VersionCompatibleNative"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectFile_VersionCompatibleConvert {
            get {
                return ((string)(this["ProjectFile_VersionCompatibleConvert"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string ProjectFile_Version_Actual {
            get {
                return ((string)(this["ProjectFile_Version_Actual"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuiAbl Database")]
        public string FileAssociation_ExtensionDescription {
            get {
                return ((string)(this["FileAssociation_ExtensionDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuiAbl.Database")]
        public string FileAssociation_ExtensionFile {
            get {
                return ((string)(this["FileAssociation_ExtensionFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project_Symbol.ico")]
        public string FileAssociation_ExtensionIconFile {
            get {
                return ((string)(this["FileAssociation_ExtensionIconFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuiAbl__v{0}__Setup.exe")]
        public string AppUpdate_SetupSearchPattern {
            get {
                return ((string)(this["AppUpdate_SetupSearchPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OliverKind")]
        public string AppUpdate_Owner {
            get {
                return ((string)(this["AppUpdate_Owner"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OLKI.Programme.QuiAbl")]
        public string AppUpdate_Name {
            get {
                return ((string)(this["AppUpdate_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Changelog.txt")]
        public string AppUpdate_ChangeLog {
            get {
                return ((string)(this["AppUpdate_ChangeLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSV-Datei (*.csv)|*.csv|Alle Dateien (*.*)|*.*")]
        public string CSVfile_FilterList {
            get {
                return ((string)(this["CSVfile_FilterList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CSVfile_FilterIndex {
            get {
                return ((int)(this["CSVfile_FilterIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("csv")]
        public string CSVfile_DefaultExtension {
            get {
                return ((string)(this["CSVfile_DefaultExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("|")]
        public string RecentFiles_Seperator {
            get {
                return ((string)(this["RecentFiles_Seperator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".jpg")]
        public string ScanedImages_DefaultExtension {
            get {
                return ((string)(this["ScanedImages_DefaultExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jpeg")]
        public global::System.Drawing.Imaging.ImageFormat ScanedImages_DefaultFormat {
            get {
                return ((global::System.Drawing.Imaging.ImageFormat)(this["ScanedImages_DefaultFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gescantes Bild")]
        public string ScanedImages_DefaultFileName {
            get {
                return ((string)(this["ScanedImages_DefaultFileName"]));
            }
        }
    }
}
