//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.QuiAbl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuiAblDb")]
        public string ProjectFile_DefaultExtension {
            get {
                return ((string)(this["ProjectFile_DefaultExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quittungsdatenbank (*.QuiAblDb)|*.QuiAblDb|QuiAbl (*.xml)|*.xml|Alle Dateien (*.*" +
            ")|*.*")]
        public string ProjectFile_FilterList {
            get {
                return ((string)(this["ProjectFile_FilterList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ProjectFile_FilterIndex {
            get {
                return ((int)(this["ProjectFile_FilterIndex"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string ProjectFile_DefaultPath {
            get {
                return ((string)(this["ProjectFile_DefaultPath"]));
            }
            set {
                this["ProjectFile_DefaultPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1;2")]
        public string ProjectFile_VersionCompatibleNative {
            get {
                return ((string)(this["ProjectFile_VersionCompatibleNative"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectFile_VersionCompatibleConvert {
            get {
                return ((string)(this["ProjectFile_VersionCompatibleConvert"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool Internal_SettingsUpgradet {
            get {
                return ((bool)(this["Internal_SettingsUpgradet"]));
            }
            set {
                this["Internal_SettingsUpgradet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string Startup_DefaultFileOpen {
            get {
                return ((string)(this["Startup_DefaultFileOpen"]));
            }
            set {
                this["Startup_DefaultFileOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool Startup_DefaultLoadEmptyProject {
            get {
                return ((bool)(this["Startup_DefaultLoadEmptyProject"]));
            }
            set {
                this["Startup_DefaultLoadEmptyProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd.MM.yyyy")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string DateFormat {
            get {
                return ((string)(this["DateFormat"]));
            }
            set {
                this["DateFormat"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string ProjectFile_Version_Actual {
            get {
                return ((string)(this["ProjectFile_Version_Actual"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool FileAssociation_CheckOnStartup {
            get {
                return ((bool)(this["FileAssociation_CheckOnStartup"]));
            }
            set {
                this["FileAssociation_CheckOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuiAbl Database")]
        public string FileAssociation_ExtensionDescription {
            get {
                return ((string)(this["FileAssociation_ExtensionDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuiAbl.Database")]
        public string FileAssociation_ExtensionFile {
            get {
                return ((string)(this["FileAssociation_ExtensionFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project_Symbol.ico")]
        public string FileAssociation_ExtensionIconFile {
            get {
                return ((string)(this["FileAssociation_ExtensionIconFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public int ScanDefaultResolution {
            get {
                return ((int)(this["ScanDefaultResolution"]));
            }
            set {
                this["ScanDefaultResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool TreeView_BillClasses_ExpandAllDefault {
            get {
                return ((bool)(this["TreeView_BillClasses_ExpandAllDefault"]));
            }
            set {
                this["TreeView_BillClasses_ExpandAllDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool TreeView_BillClasses_AllowCollaps {
            get {
                return ((bool)(this["TreeView_BillClasses_AllowCollaps"]));
            }
            set {
                this["TreeView_BillClasses_AllowCollaps"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuiAbl__v{0}__Setup.exe")]
        public string AppUpdate_SetupSearchPattern {
            get {
                return ((string)(this["AppUpdate_SetupSearchPattern"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool AppUpdate_CheckAtStartUp {
            get {
                return ((bool)(this["AppUpdate_CheckAtStartUp"]));
            }
            set {
                this["AppUpdate_CheckAtStartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OliverKind")]
        public string AppUpdate_Owner {
            get {
                return ((string)(this["AppUpdate_Owner"]));
            }
            set {
                this["AppUpdate_Owner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OLKI.Programme.QuiAbl")]
        public string AppUpdate_Name {
            get {
                return ((string)(this["AppUpdate_Name"]));
            }
            set {
                this["AppUpdate_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Changelog.txt")]
        public string AppUpdate_ChangeLog {
            get {
                return ((string)(this["AppUpdate_ChangeLog"]));
            }
            set {
                this["AppUpdate_ChangeLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public int ScanDefaultColorMode {
            get {
                return ((int)(this["ScanDefaultColorMode"]));
            }
            set {
                this["ScanDefaultColorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string RecentFiles_FileList {
            get {
                return ((string)(this["RecentFiles_FileList"]));
            }
            set {
                this["RecentFiles_FileList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public int RecentFiles_MaxLength {
            get {
                return ((int)(this["RecentFiles_MaxLength"]));
            }
            set {
                this["RecentFiles_MaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("|")]
        public string RecentFiles_Seperator {
            get {
                return ((string)(this["RecentFiles_Seperator"]));
            }
            set {
                this["RecentFiles_Seperator"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSV-Datei (*.csv)|*.csv|Alle Dateien (*.*)|*.*")]
        public string CSVfile_FilterList {
            get {
                return ((string)(this["CSVfile_FilterList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CSVfile_FilterIndex {
            get {
                return ((int)(this["CSVfile_FilterIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("csv")]
        public string CSVfile_DefaultExtension {
            get {
                return ((string)(this["CSVfile_DefaultExtension"]));
            }
        }
    }
}
