//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.QuiAbl.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Stringtable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stringtable() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Programme.QuiAbl.Properties.Stringtable", typeof(Stringtable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inkompatible Datei! ähnelt.
        /// </summary>
        internal static string _0x0001c {
            get {
                return ResourceManager.GetString("0x0001c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Projektdatei ist nicht mit dieser Progammversion kompatibel. ähnelt.
        /// </summary>
        internal static string _0x0001m {
            get {
                return ResourceManager.GetString("0x0001m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungespeicherte Änderungen! ähnelt.
        /// </summary>
        internal static string _0x0002c {
            get {
                return ResourceManager.GetString("0x0002c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im aktuellen Projekt befinden sich ungespeicherte Änderungen. Wenn Sie fortfahren gehen diese Änderungen verloren.
        ///
        ///Möchten Sie fortfahren? ähnelt.
        /// </summary>
        internal static string _0x0002m {
            get {
                return ResourceManager.GetString("0x0002m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt öffnen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x0003c {
            get {
                return ResourceManager.GetString("0x0003c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;{0}&quot; konnte nicht geöffnet werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0003m {
            get {
                return ResourceManager.GetString("0x0003m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x0004c {
            get {
                return ResourceManager.GetString("0x0004c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Projekt konnte nicht in die Datei &quot;{0}&quot; gespeichert werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0004m {
            get {
                return ResourceManager.GetString("0x0004m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt öffnen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x0005c {
            get {
                return ResourceManager.GetString("0x0005c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Lesen der Projektdatei.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0005m {
            get {
                return ResourceManager.GetString("0x0005m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei überschreiben? ähnelt.
        /// </summary>
        internal static string _0x0006c {
            get {
                return ResourceManager.GetString("0x0006c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Datei sind bereits Daten angehangen. Wollen Sie diese überschreiben? ähnelt.
        /// </summary>
        internal static string _0x0006m {
            get {
                return ResourceManager.GetString("0x0006m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Lesen der Datei! ähnelt.
        /// </summary>
        internal static string _0x0007c {
            get {
                return ResourceManager.GetString("0x0007c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei
        ///{0}
        ///konnte nicht angehangen werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0007m {
            get {
                return ResourceManager.GetString("0x0007m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei öffnen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x0008c {
            get {
                return ResourceManager.GetString("0x0008c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei konnte nicht geöffnet werden.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0008m {
            get {
                return ResourceManager.GetString("0x0008m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabe entspricht keinem gültigen Datum. ähnelt.
        /// </summary>
        internal static string _0x0009 {
            get {
                return ResourceManager.GetString("0x0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- Keine Benennung -- ähnelt.
        /// </summary>
        internal static string _0x000A {
            get {
                return ResourceManager.GetString("0x000A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Projekt ähnelt.
        /// </summary>
        internal static string _0x000B {
            get {
                return ResourceManager.GetString("0x000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initialisierung ähnelt.
        /// </summary>
        internal static string _0x000C {
            get {
                return ResourceManager.GetString("0x000C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prüfe Version ähnelt.
        /// </summary>
        internal static string _0x000D {
            get {
                return ResourceManager.GetString("0x000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Daten 1/3: Rechnungen ähnelt.
        /// </summary>
        internal static string _0x000E {
            get {
                return ResourceManager.GetString("0x000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Daten 2/3: Kategorien ähnelt.
        /// </summary>
        internal static string _0x000F {
            get {
                return ResourceManager.GetString("0x000F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Daten 3/3: Firmen ähnelt.
        /// </summary>
        internal static string _0x0010 {
            get {
                return ResourceManager.GetString("0x0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Eingabemaske ähnelt.
        /// </summary>
        internal static string _0x0011 {
            get {
                return ResourceManager.GetString("0x0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt öffnen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x0012c {
            get {
                return ResourceManager.GetString("0x0012c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei ist bereits geöffnet und kann nicht erneut geöffnet werden. ähnelt.
        /// </summary>
        internal static string _0x0012m {
            get {
                return ResourceManager.GetString("0x0012m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern vorbereiten ähnelt.
        /// </summary>
        internal static string _0x0013 {
            get {
                return ResourceManager.GetString("0x0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schreibe in Datei ähnelt.
        /// </summary>
        internal static string _0x0014 {
            get {
                return ResourceManager.GetString("0x0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern? ähnelt.
        /// </summary>
        internal static string _0x0015c {
            get {
                return ResourceManager.GetString("0x0015c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen an Projekt &quot;{0}&quot; vor dem Schließen speichern?
        ///
        ///Ihre Änderungen gehen verloren, wenn Sie diese nicht speichern. ähnelt.
        /// </summary>
        internal static string _0x0015m {
            get {
                return ResourceManager.GetString("0x0015m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standardordner der bei der Dateiauswahl angezeigt werden soll ähnelt.
        /// </summary>
        internal static string _0x0016 {
            get {
                return ResourceManager.GetString("0x0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanfehler! ähnelt.
        /// </summary>
        internal static string _0x0017c {
            get {
                return ResourceManager.GetString("0x0017c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Scannen des Dokumentes.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0017m {
            get {
                return ResourceManager.GetString("0x0017m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei öffnen? ähnelt.
        /// </summary>
        internal static string _0x0018c {
            get {
                return ResourceManager.GetString("0x0018c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei wurde gespeichert. Soll die Datei jetzt geöffnet werden? ähnelt.
        /// </summary>
        internal static string _0x0018m {
            get {
                return ResourceManager.GetString("0x0018m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschneiden nicht möglich! ähnelt.
        /// </summary>
        internal static string _0x0019c {
            get {
                return ResourceManager.GetString("0x0019c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie zuerst einen Bereich zum Zuschneiden aus. ähnelt.
        /// </summary>
        internal static string _0x0019m {
            get {
                return ResourceManager.GetString("0x0019m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Import von CSV-Daten. ähnelt.
        /// </summary>
        internal static string _0x001Ac {
            get {
                return ResourceManager.GetString("0x001Ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die CSV-Daten konnten nicht oder nur teilweise importiert werden.
        ///Bitte überprüfen Sie ob die Datei existiert und ob sie dem richtigen Format entspricht.
        ///
        ///{0}
        ///
        ///Bitte überprüfen Sie welche Daten importiert wurden. ähnelt.
        /// </summary>
        internal static string _0x001Am {
            get {
                return ResourceManager.GetString("0x001Am", resourceCulture);
            }
        }
    }
}
